webhook_url: https://discord.com/api/webhooks/1218995079876706449/kdTnRpgYl-GqO7iSjUiMLFSaAmqsAKY9tMbYkYQ5VcEwjNowYqiyqEpOxMgY0c5JaFtm
channel_id: 1218984588018454548
site_name:
    - linkedin
search_term: software engineer,devops engineer,site reliability engineer,cloud engineer
location: Edinburgh, Scotland, United Kingdom
results_wanted: 10
hours_old: 72
country_indeed: uk
